Mesage view画面作成
KatsuhiroHonma/chat-space pull request #3
Opened 2019-02-08 08:26 UTC by KatsuhiroHonma

2019-02-08 08:29 UTC, KatsuhiroHonma commented
#WHAT
chatspaceのviewを作成した

#WHY
本アプリケーションについて必須であるため

2019-02-08 08:42 UTC, yuki-uchida requested changes

2019-02-08 08:42 UTC, yuki-uchida commented on app/assets/stylesheets/modules/main.scss
> +    .group {
全体的に、もう一度BEMという命名規則を意識して書き直してみてください。https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-02-10 06:12 UTC, KatsuhiroHonma commented on app/assets/stylesheets/modules/main.scss
> +    .group {
上記修正しました。

2019-02-10 06:13 UTC, TOMARUMARU commented on app/assets/stylesheets/modules/side.scss
> +  // padding: 20px 10px 20px 20px;
不要なコメントアウトは消しましょう

2019-02-10 06:13 UTC, TOMARUMARU commented on app/helpers/messages_helper.rb
> +module MessagesHelper
使用してないherlperファイルは消しましょう

2019-02-10 06:13 UTC, TOMARUMARU commented on config/routes.rb
> +  resources :messages, only: :index
rootパスに設定しましょう

2019-02-10 06:34 UTC, KatsuhiroHonma commented on app/assets/stylesheets/modules/side.scss
> +  // padding: 20px 10px 20px 20px;
上記修正しました

2019-02-10 06:34 UTC, KatsuhiroHonma commented on app/helpers/messages_helper.rb
> +module MessagesHelper
上記修正しました

2019-02-10 06:35 UTC, KatsuhiroHonma commented on config/routes.rb
> +  resources :messages, only: :index
上記修正しました

2019-02-10 06:37 UTC, ghost reviewed
実装したビューのキャプチャをこちらに添付してください。

2019-02-10 06:40 UTC, KatsuhiroHonma commented
> 実装したビューのキャプチャをこちらに添付してください。

以下が実装したビューです
https://gyazo.com/d3ecfdc1c1143c9bb29bb200364010a6

2019-02-10 06:44 UTC, kuroko918 commented on test/controllers/messages_controller_test.rb
> +class MessagesControllerTest < ActionDispatch::IntegrationTest
このテストファイルもここでは使用しないので消しておきましょう！

2019-02-10 06:48 UTC, KatsuhiroHonma commented on test/controllers/messages_controller_test.rb
> +class MessagesControllerTest < ActionDispatch::IntegrationTest
上記修正しました

2019-02-10 06:51 UTC, kuroko918 commented
修正が反映されていないので、確認お願いします！

2019-02-10 06:53 UTC, KatsuhiroHonma commented
プッシュしてませんでした。。すみません。。
確認お願いします。

2019-02-10 06:54 UTC, TOMARUMARU approved these changes
LGTM

2019-02-10 06:55 UTC, merged